version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/springdb
    depends_on:
          - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
